# Generated by Django 5.2.5 on 2025-11-24 10:57

import accounting.helper_functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KharjType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "code",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=51,
                        verbose_name="باقیمانده",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kharj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="عنوان خرج")),
                ("description", models.TextField(blank=True, verbose_name="توضیح خرج")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "شنبه"),
                            (2, "یکشنبه"),
                            (3, "دوشنبه"),
                            (4, "سه\u200cشنبه"),
                            (5, "چهارشنبه"),
                            (6, "پنجشنبه"),
                            (7, "جمعه"),
                        ],
                        default=accounting.helper_functions.current_shamsi_day_of_week,
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=accounting.helper_functions.current_shamsi_day_of_month,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="روز ماه",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        default=accounting.helper_functions.current_shamsi_month,
                        verbose_name="ماه",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=accounting.helper_functions.current_shamsi_year,
                        verbose_name="سال",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=51,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قیمت",
                    ),
                ),
                (
                    "type",
                    models.ManyToManyField(
                        to="accounting.kharjtype", verbose_name="نوع خرج"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
