# Generated by Django 5.2.5 on 2025-11-24 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kharj",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="kharjtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="kharjtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="moneyholder",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="moneyholder",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="kharj",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="kharj",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="kharj",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="زمان آخرین ویرایش"),
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="code",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="کد خرج",
            ),
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="title",
            field=models.CharField(max_length=255, verbose_name="نوع خرج"),
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="زمان آخرین ویرایش"),
        ),
        migrations.AlterField(
            model_name="moneyholder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="moneyholder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="زمان آخرین ویرایش"),
        ),
    ]
