# Generated by Django 5.1.14 on 2025-11-24 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_kharj_is_active_kharjtype_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("title", models.CharField(max_length=255, verbose_name="مقر درآمد")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=51,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مقدار درآمد",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LentFrom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="شخص یا جایی که ازش قرض گرفتم"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=51,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مقداری که قرض گرفتم",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LentTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="شخص یا جایی که بهش قرض دادم"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=51,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مقداری که قرض دادم",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="kharj",
            options={},
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="code",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="کد خرج",
            ),
        ),
        migrations.AlterField(
            model_name="kharjtype",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="نوع خرج"),
        ),
        migrations.AlterField(
            model_name="moneyholder",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="نام"),
        ),
    ]
