# Generated by Django 5.2.5 on 2025-11-24 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_income_lentfrom_lentto_alter_kharj_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderLents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("title", models.CharField(max_length=255, verbose_name="مورد")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=51,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مقداری که قرض دادم",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
